name: FormatCheck & Build & UnitTest

on:
  push:
    branches: [ master, feature/** ]

jobs:
  format-check_build_unit-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0
    - name: Install dotnet format
      run: dotnet tool install -g dotnet-format --version 5.1.250801
    - name: format-check-whitespace
      run: dotnet format whitespace --verify-no-changes --verbosity q
    - name: format-check-style
      run: dotnet format style --verify-no-changes --verbosity q
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
