name: FormatCheck & Build & UnitTest

on:
  push:
    branches: [ master, feature/** ]

jobs:
  format-check_build_unit-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dotnet format
      run: dotnet tool install -g dotnet-format
    - name: format-check
      run: dotnet format --check --verbosity q --dry-run
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
