name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, feature/** ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dotnet format
      run: dotnet tool install -g dotnet-format
    - name: format-check
      run: cd ./Diary-Sample && dotnet format --check --verbosity q --dry-run
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: cd ./Diary-Sample && dotnet build --configuration Release --no-restore
    - name: Test
      run: cd ./Diary-Sample && dotnet test --no-restore --verbosity normal
