name: E2E TEST

on:
  push:
    branches: [ master, feature/** ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REG_SUIT_CLIENT_ID: ${{ secrets.REG_SUIT_CLIENT_ID }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: db volume permission change
        run: chmod 777 Diary-Sample/docker/db/data
      - name: db startup
        run: docker-compose -f Diary-Sample/docker-compose.yml up -d
      - name: app build
        run: docker build -f Diary-Sample/Dockerfile -t diary_sample_app_1 Diary-Sample/..
      - name: app startup
        run: docker run -d --name diary_sample_app_1 --network diary-sample_default -p 80:80 diary_sample_app_1
      - name: Entity Framework Core CLI Tool install
        run: dotnet tool install --global dotnet-ef --version 3.1.8
      - name: db migrate
        run: dotnet ef database update --project Diary-Sample
      - name: Install Cypress and run tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: e2e
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: videos
          path: e2e/cypress/videos
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: screenshots
          path: e2e/cypress/screenshots

      - name: Use Node.js v10
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: npm install
        run: yarn install --pure-lockfile
        working-directory: ./e2e
        env:
          CI: true
      - name: run visual regression test
        run: yarn run reg-suit
        working-directory: ./e2e