name: E2E TEST

on:
  push:
    branches: [ master, feature/** ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: db startup
        run: docker-compose -f Diary-Sample/docker-compose.yml up -d
      - name: app build
        run: docker build -f Diary-Sample/Dockerfile -t diary_sample_app_1 Diary-Sample/..
      - name: app startup
        run: docker run -d --name diary_sample_app_1 --network diary-sample_default -p 80:80 diary_sample_app_1
      - name: Install Cypress and run tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: e2e
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: videos
          path: e2e/cypress/videos